#! /bin/bash

logfile=/tmp/gitbin/gitbin.err
CLNT=$(hostname)

if [ ! -d /tmp/gitbin ]; then
  mkdir /tmp/gitbin
fi

echo "" > $logfile

pushd /home/pi/gitbin 2>$logfile 1>&2

./01-update-scripts.sh | tee -a $logfile | logger -p local7.info -t 01-update-scripts

./11-get-temp.py & ./12-get-load.py & ./13-get-nettraffic.py & ./14-get-memory.py & ./31-xml-status.sh & wait 2>$logfile 1>&2

if [ $CLNT == "rbups" ]; then
  ./16-get-upsstate.py 2>$logfile 1>&2
fi

./99-upload-data.sh 2>$logfile 1>&2

popd 2>$logfile 1>&2
