#! /bin/bash

MOUNTPOINT=/mnt/share1
MOUNTDRIVE=10.0.1.220:/srv/array1/rbin
HOST=$(hostname)

# Mount the share containing the scripts
sudo mount $MOUNTDRIVE $MOUNTPOINT

# Check if the drive actually got mounted or not
if grep -qs '/mnt/share1 ' /proc/mounts; then
    # It's mounted.

    # Check for the 'flag' file which should indicate that
    # updated scripts are present.
    # Copy the scripts and remove the flag.
    if [ -e $MOUNTPOINT/$HOST/run/flag ]; then
        cp $MOUNTPOINT/$HOST/run/* ~/bin/run/
        rm $MOUNTPOINT/$HOST/run/flag
        rm /home/pi/bin/run/flag
        logger -p local7.info -t 00-update-scripts "New scripts downloaded ($$)"
    fi
    if [ -e /home/pi/bin/run/flag ]; then
        cp $MOUNTPOINT/$HOST/run/* ~/bin/run/
        rm $MOUNTPOINT/$HOST/run/flag
        rm /home/pi/bin/run/flag
        logger -p local7.info -t 00-update-scripts "New scripts downloaded ($$)"
    fi
    # Unmount the drive again
    sudo umount $MOUNTPOINT
fi
