#! /bin/bash

minute=$(date "+%M")

if [ $minute -eq "42" ]; then
  #echo $(date) >> /tmp/dt.txt
  # Update the git scripts once every hour
  cd /home/pi/bin/gitrun
  git fetch origin && git reset --hard origin/test && git clean -f -d
fi
